<?php

include_once('header.phtml');

?>


<?php

  if(!empty($_REQUEST['alert'])){
?>

<div class="alert">
    <?php 
      switch( $_REQUEST['alert']){

        case 'userCreated':
          echo "Usuario já registrado";
        break;

        case 'wrongRegister':
          echo 'usuario ou senha incorreto(s)';
        break;

        case 'unlogged':
          echo 'Registre-se ou cadastre-se antes';
        break;

      }
    
    ?>
</div>
  <?php } ?>
  
<div class="container-wrap">
  <div class="container">


    <div class="form-div">

      <form action="enter" method="post">

      <div class="container-title">
        <h1 class="title">Parallax</h1>
      </div>

        <div class="avatar">
          <img src="img/avatar.svg" alt="user">
          <h2>Bem Vindo</h2>
        </div>

          <div class="input-div name">

              <div class="icon">
                  <i class="fas fa-user"></i>
              </div>
              
              <div class="div">
                  <input name="name" placeholder="username" type="text">
              </div>

          </div>


          <div class="input-div password">

            <div class="icon">
              <i class="fas fa-lock"></i>
            </div>

            <div class="div">
              <input name="password" placeholder="password" type="password">
            </div>

          </div>
          
          <div class="button-div">
            <button name="login" value='signUp'>SignUp</button>
            <button name="login" value='signIn'>SignIn</button>
          </div>

      </form>
    </div>

    
  </div>
</div>

<?php

include_once('footer.phtml');
?>