<?php

include_once('header.phtml');

?>
<div class="container-wrap">
  <div class="container">


    <div class="form-div">

      <form action="enter" method="post">

      <div class="container-title">
        <h1 class="title">Parallax</h1>
      </div>

        <div class="avatar">
          <img src="img/avatar.svg" alt="user">
          <h2>Bem Vindo</h2>
        </div>

          <div class="input-div name">

              <div class="icon">
                  <i class="fas fa-user"></i>
              </div>
              
              <div class="div">
                  <input name="name" placeholder="username" type="text">
              </div>

          </div>


          <div class="input-div password">

            <div class="icon">
              <i class="fas fa-lock"></i>
            </div>

            <div class="div">
              <input name="password" placeholder="password" type="password">
            </div>

          </div>
          
          <div class="button-div">
            <button name="login" value='signIn'>SignUp</button>
            <button name="login" value='signUp'>SignIn</button>
          </div>

      </form>
    </div>

    
  </div>
</div>

<?php

include_once('footer.phtml');
?>